server:
    port: 8085


spring:
    cloud:
        gateway:
            routes:
                - id: InventoryModule
                  uri: http://localhost:8083/
                  predicates:
                  - Path=/Inventory/**
